### PR TITLE
Migrated to Elixir 1.5 and Timex 3.1

### PR DESCRIPTION
**Pull request by f34nk**

### CODE REVIEW

**Comment by jfacorro** [comment]
@f34nk Thank you for this PR 😄. 

It seems that the Travis CI build is failing because Elixir's version specified in the `.travis.yml` file is still [`1.3.2`](https://github.com/jfacorro/Eden/blob/master/.travis.yml#L3).

Could you please update that file?

**Comment by f34nk** [comment]
I would exclude Elixir 1.3 from travis...

**Comment by jfacorro** [comment]
@f34nk I agree. In that case the major version for Eden could be bumped since these changes are not backward compatible.

**Comment by jfacorro** [comment]
Awesome stuff, thanks!

**Comment by jfacorro** [comment]
Created release `2.0.0`

**Pull request merged**
